// packages/frontend/next/src/components/footer/Footer1.tsx
import Image from "next/image";
import { FaFacebookF, FaLinkedinIn, FaInstagram, FaXTwitter } from "react-icons/fa6";

import Link from "next/link";

export default function Footer() {
    const info = [
        "Address: 123 xxx-xxxx",
        "Call Us: (x) xxx-xxxx",
        "Email: email@contact.com",
      ];
    
      const accountLinks = ["Link1", "Link2", "Link3"];
    
      const usefulLinks = [<Link href="about">About Us</Link>, <Link href="contact">Contact</Link>];
    
      const helpCenterLinks = [
        <Link href="/policy">Privacy Policy</Link>,
        <Link href="/terms">Terms of Use</Link>,
      ];
      const social = [<FaFacebookF />, <FaLinkedinIn />, <FaInstagram />, <FaXTwitter />];
      const date = new Date().getFullYear();
  return (
    <div className="container">
    <ul className="flex pt-12 flex-wrap flex-col lg:flex-row items-center justify-between border-b pb-6">
    <li className="self-start">
      <div className="flex self-start items-center mb-4 w-fit cursor-pointer">
        {/* <Image src={"https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png"} width={100} height={100} alt="icon"/> */}
        <div className="ml-1">
          <div className="text-xl font-bold ">RapidStack</div>
        </div>
      </div>
      {info.map((x, id) => (
        <p
          key={id}
          className="my-2  duration-300  cursor-pointer"
        >
          {x}
        </p>
      ))}
      <div className="w-full">
        <input
          type="email"
          className="border p-2 w-full outline-none bg-white"
          
          placeholder="Enter your email address"
        />
        <button  className="bg-white text-black py-2 px-4 mt-1">
          Subscribe
        </button>
      </div>
    </li>
    <li className="self-start">
      <h1 className="font-bold text-xl  mb-2 lg:mb-4">Account</h1>
      {accountLinks.map((x, id) => (
        <p
          key={id}
          className=" duration-300  cursor-pointer my-2"
        >
          {x}
        </p>
      ))}
    </li>
    <li className="self-start">
      <h1 className="font-bold text-xl  mb-2 lg:mb-4">Useful links</h1>
      {usefulLinks.map((x, id) => (
        <p
          key={id}
          className=" duration-300  cursor-pointer my-2"
        >
          {x}
        </p>
      ))}
    </li>
    <li className="self-start">
      <h1 className="font-bold text-xl  mb-2 lg:mb-4">Help Center</h1>
      {helpCenterLinks.map((x, id) => (
        <p
          key={id}
          className=" duration-300  cursor-pointer my-2"
        >
          {x}
        </p>
      ))}
    </li>
  </ul>
  <div className="py-6 flex flex-col gap-y-4 md:flex-row md:gap-y-0 items-center justify-between">
      <div className="">
        &copy; {date}, All rights reserved
      </div>
      <div>
        {/* <img src={payment} alt="payment img" /> */}
      </div>
      <ul className="flex gap-4">
        {social.map((x, id) => (
          <li
            key={id}
            className="text-2xl text-white p-2 rounded-full cursor-pointer"
          >
            {x}
          </li>
        ))}
      </ul>
    </div>
  </div>
  );
}

// packages/frontend/nuxt/components/footer/Footer1.vue
<template>
  <footer class="bg-gray-800 text-white py-10">
    <div
      class="max-w-screen-xl mx-auto flex flex-col md:flex-row justify-between items-center px-4">
      <div class="text-center md:text-left mb-6 md:mb-0">
        <h3 class="text-2xl font-bold">Stay Connected</h3>
        <p class="text-gray-400 mt-2">
          Subscribe to our newsletter for the latest updates.
        </p>
        <div class="mt-4">
          <input
            type="email"
            placeholder="Your email"
            class="p-2 rounded-l-lg border border-gray-300 focus:outline-none focus:border-blue-500" />
          <button
            class="bg-blue-600 text-white p-2 rounded-r-lg hover:bg-blue-700">
            Subscribe
          </button>
        </div>
      </div>

      <div
        class="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-10">
        <div>
          <h4 class="font-semibold">Links</h4>
          <ul class="mt-2 space-y-1">
            <li>
              <NuxtLink to="/" class="hover:text-blue-500">Home</NuxtLink>
            </li>
            <li>
              <NuxtLink to="/about" class="hover:text-blue-500">About</NuxtLink>
            </li>
            <li>
              <NuxtLink to="/services" class="hover:text-blue-500"
                >Services</NuxtLink
              >
            </li>
            <li>
              <NuxtLink to="/contact" class="hover:text-blue-500"
                >Contact</NuxtLink
              >
            </li>
          </ul>
        </div>

        <div>
          <h4 class="font-semibold">Follow Us</h4>
          <div class="flex space-x-4 mt-2">
            <a href="#" class="hover:text-blue-500">Facebook</a>
            <a href="#" class="hover:text-blue-500">Twitter</a>
            <a href="#" class="hover:text-blue-500">Instagram</a>
            <a href="#" class="hover:text-blue-500">LinkedIn</a>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center mt-6 border-t border-gray-700 pt-4">
      <p class="text-gray-400 text-sm">
        © 2024 Your Company. All rights reserved.
      </p>
    </div>
  </footer>
</template>

<script setup></script>

<style scoped></style>
